### ISSUE TITLE
1.9 Update?

### ISSUE THREAD

**Issue by astr1al** [slipswhitley/SketchMap#5]
Just wondering if you plan on updating this plugin for 1.9? As of now there are no errors but sketchmaps don't show up even tried making new ones without much luck. Hope you are still around! :)

**Comment by trainphreak** [comment]
I haven't made any changes to my fork since 1.9 came out (and those changes weren't related to 1.9 anyway) and I have no trouble creating sketchmaps in 1.9. Can you provide more details, such as plugin and Spigot versions, the exact command you are running, and a copy of your console log (use Pastebin please)?

**Comment by astr1al** [comment]
This server is running CraftBukkit version git-Spigot-5a40365-f631379 (MC: 1.9.2) (Implementing API version 1.9.2-R0.1-SNAPSHOT)[m

Even though I tried downloading the latest versions of SketchMap from Spigot and Bukkit it says I am running SketchMap v1.0.0

I tried running /sketchmap create mau5 https://i.ytimg.com/vi/4kepqYBMw-g/maxresdefault.jpg 3:2
then /sketchmap place mau5
but it just places maps on the wall w/ nothing on them.

Here is everything in my console log for Sketchmap http://pastebin.com/s6uyQE8W
The full log is too big for pastebin, and there are no errors from other plugins.

**Comment by trainphreak** [comment]
Have you tried using PNG source image instead of JPG?

**Comment by astr1al** [comment]
Sorry for the late reply, have been busy :(
Tested on 2 png images without any luck.
